### ISSUE TITLE
Use SSH Key instead of password

### ISSUE THREAD

**Issue by thebeardedgeek** [richardschoen/workwithibmipdm#2]
Create a way to use ssh key instead of having to enter a password.

**Comment by richardschoen** [comment]
Yep. I just haven't gotten it done yet 👍

**Comment by richardschoen** [comment]
Can now use SSH key files for selected sites. SSH key file must be in PuTTYgen format. This is a limitation imposed by the Renci.SshNet.dll assembly.  You can reformat OpenSSH keys to PuTTYgen format using puTTYgen.    
https://www.puttygen.com

**Comment by richardschoen** [comment]
V1.0.1.5 supports SSH key files now.
