### ISSUE TITLE
About xmlservice-cli package

### ISSUE THREAD

**Issue by MarcoDeSenas** [richardschoen/workwithibmipdm#4]
Hello
I am trying to use WorkWithIBMiPDM on [pub400.com](https://pub400.com/). Installing specific files in /QOpenSys/pkgs/bin is not allowed and not an option on this system.
xmlservice-cli is installed on this system and, of course, xmlservicemb-cli is not. What is the impact of not being able to use MB package?

I have noticed that there is a "xmlservicecli" parameter in settings file. However, I always have an error message whatever the value I put. If put xmlserviceMB-cli, the error relates that this file is not available on the host and cannot be uploaded. If I put xmlservice-cli, the error relates that this file is not available locally.

Thanks in advance
Marc

**Comment by richardschoen** [comment]
Right now the IBM version of xmlservice-cli is an issue because it does not allow us to set the cdata parameter which means XML data can get mangled from our DB queries. 

Can you have someone upload the following file manually to ```/QOpenSys/pkgs/bin/xmlservicemb-cli``` 
File to upload: ```\Program Files (x86)\MobiGoGo\MBWorkWithIBMi\xmlservicemb-cli```

**Comment by richardschoen** [comment]
Another thought is if you're using PUB400, place the xmlservicemb-cli manually into your home directory and update the setting accordingly in the AppSettings.xml file.

I'll also do a PUB400 test.

**Comment by MarcoDeSenas** [comment]
> Another thought is if you're using PUB400, place the xmlservicemb-cli manually into your home directory and update the setting accordingly in the AppSettings.xml file.
Good idea, I will test that ASAP.
> 
> I'll also do a PUB400 test.

**Comment by richardschoen** [comment]
OK, here's the loose list of instructions for PUB400:

Upload the following file manually to ```/home/<YOURUSERID>/xmlservicemb-cli```
File to upload: ``C:\Program Files (x86)\MobiGoGo\MBWorkWithIBMi\xmlservicemb-cli``

After upload, log on via putty and make the xmlservicemb-cli program executable: 
```chmod +x /home/<YOURUSERID>/xmlservicemb-cli```

Launch work with IBM i app and go to ```File/Settings``` to edit ```AppSettings.xml``` 

Set the following settings for optimal use with PUB400.COM:
```
Set your system list with PUB400. Or you can just type into the Work with IBM i UI
  <Setting>
    <SettingName>ibmisystemlist</SettingName>
    <SettingValue>PUB400.COM:2022</SettingValue>
  </Setting>
Turn off attempts to load a list of all libraries. Too many to list
 <Setting>
    <SettingName>loadalllibrarylist</SettingName>
    <SettingValue>False</SettingValue>
  </Setting>
Set your libraries, which will show in the source library combo. Or you can just type source library in the combo box
  <Setting>
    <SettingName>sourcelibrarylist</SettingName>
    <SettingValue>RICHARDS1,RICHARDS2</SettingValue>
  </Setting>
Set new location to your home directory for xmlservicemb-clli
  <Setting>
    <SettingName>xmlservicecli</SettingName>
    <SettingValue>/home/<YOURUSERID>/xmlservicemb-cli</SettingValue>
  </Setting>
```

**Comment by MarcoDeSenas** [comment]
Thanks, works fine now. I had a first failed test just after your initial tip, but forgot to make xmlservicemb-cli executable.

Note : port is **2222** on pub400.com, not **2022**
