### ISSUE TITLE
XMLSERVICE library public authority

### ISSUE THREAD

**Issue by MarcoDeSenas** [richardschoen/workwithibmipdm#6]
What is the impact of having XMLSERVICE library public authority set to *EXCLUDE?

During my first tests on pub400.com, this library was excluded. I asked pub400.com owners if it was possible to set this to *USE. They agreed and proceeded. Now, that my issues with xmlservicemb-cli is solved, I believe that everything is working fine.

pub400.com owners claim that normal delivery of this IBM XMLSERVICE library is *EXCLUDE. Should I agree with them so that they set it back to *EXCLUDE or do we have to keep it as *USE?

**Comment by richardschoen** [comment]
On my V7R3 system library: ```QXMLSERV``` and the following objects are all set to *PUBLIC/*USE.

```
XMLCGI      *PGM        RPGLE 
XMLMAIN     *PGM        RPGLE 
XMLSERVICE  *PGM        RPGLE 
XMLVER      *PGM        RPGLE 
XMLSTOREDP  *SRVPGM     RPGLE 
```

So I'm guessing the library and objects on PUB400 would need to be the same.
